
services:
  # 🛢 PostgreSQL 17 with pgvector 0.8.0
  postgres:
    image: pgvector/pgvector:0.8.0-pg17
    environment:
      POSTGRES_USER: scraper
      POSTGRES_PASSWORD: scraperpass
      POSTGRES_DB: scraperdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./db/init_pgvector.sh:/docker-entrypoint-initdb.d/init_pgvector.sh

  # 🐍 Flask Backend API (via Poetry)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: python app.py
    ports:
      - "5001:5000"
    environment:
      DATABASE_URL: postgresql://scraper:scraperpass@postgres:5432/scraperdb
      OLLAMA_HOST: http://host.docker.internal:11434
    depends_on:
      - postgres
    volumes:
      - ./backend:/app/static
      - uploads:/app/uploads

volumes:
  pgdata:
  uploads:
