# docker-compose.yml

name: llm-scraper

services:
  # PostgreSQL 17 with pgvector 0.8.0
  postgres:
    image: pgvector/pgvector:0.8.0-pg17
    environment:
      POSTGRES_USER: scraper
      POSTGRES_PASSWORD: scraperpass
      POSTGRES_DB: scraperdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./db/init_pgvector.sh:/docker-entrypoint-initdb.d/init_pgvector.sh

  # Flask Backend API
  backend:
    build: ./backend
    command: python app.py
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: postgresql://scraper:scraperpass@postgres:5432/scraperdb
    depends_on:
      - postgres
    volumes:
      - ./backend:/app
      - uploads:/app/uploads

  # React Frontend (Vite)
  frontend:
    build: ./frontend
    ports:
      - "8080:8080"
    depends_on:
      - backend
    command: npm run dev
    working_dir: /app
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  pgdata:
  uploads: