version: '3.8'

services:
  postgres:
    image: pgvector/pgvector:0.5.0-pg15
    environment:
      POSTGRES_USER: scraper
      POSTGRES_PASSWORD: scraperpass
      POSTGRES_DB: scraperdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./db/init_pgvector.sh:/docker-entrypoint-initdb.d/init_pgvector.sh

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql://scraper:scr
